services:
  pg-criteria:
    image: bitnami/postgresql:17.0.0
    container_name: pg-criteria
    restart: unless-stopped
    ports:
      - "25432:5432"
    environment:
      POSTGRES_DB: db_criteria
      POSTGRES_PASSWORD: PGCriteriaPass123
      TZ: America/Lima
      PGTZ: America/Lima
    volumes:
      - /Users/marcolopez/Workspace/volumes/ep-net/pg-criteria:/var/lib/postgresql/data
      - ./scripts/pg_criteria_init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default

networks:
  default:
    external: true
    name: employees-promotion-net
