services:
  pg-human-resources:
    image: bitnami/postgresql:17.0.0
    container_name: pg-human-resources
    restart: unless-stopped
    ports:
      - "35432:5432"
    environment:
      POSTGRES_DB: db_human_resources
      POSTGRES_PASSWORD: PGHumResPass123
      TZ: America/Lima
      PGTZ: America/Lima
    volumes:
      - /Users/marcolopez/Workspace/volumes/ep-net/pg-human-resources:/var/lib/postgresql/data
      - ./scripts/pg_human_resources_init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default

networks:
  default:
    external: true
    name: employees-promotion-net
