services:
  pg-command-promotion:
    image: bitnami/postgresql:17.0.0
    container_name: pg-command-promotion
    restart: unless-stopped
    ports:
      - "35432:5432"
    environment:
      POSTGRES_DB: db_command_promotion
      POSTGRES_PASSWORD: PGCommandPromotionPass123
      TZ: America/Lima
      PGTZ: America/Lima
    volumes:
      - /Users/marcolopez/Workspace/volumes/ep-net/pg-command-promotion:/var/lib/postgresql/data
      - ./scripts/pg_command_promotion_init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default

networks:
  default:
    external: true
    name: employees-promotion-net
