services:
  redis:
    image: redis:7.4.1
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - /Users/marcolopez/Workspace/volumes/ep-net/redis/local/data:/root/redis
      - /Users/marcolopez/Workspace/volumes/ep-net/redis/local/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - default
    environment:
      - REDIS_PASSWORD=Th3R3d1sP4ssw0rd
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
  redisinsight:
    image: redis/redisinsight:2.58
    container_name: redisinsight
    restart: unless-stopped
    ports:
      - "7071:5000"
    volumes:
      - /Users/marcolopez/Workspace/volumes/ep-net/redisinsight/data:/data
    networks:
      - default

networks:
  default:
    external: true
    name: employees-promotion-net
