services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    restart: unless-stopped
    ports:
      - "6379:6379"
      - "7071:8001"
    volumes:
      - /Users/marcolopez/Workspace/volumes/ep-net/redisinsight/data:/data
      - /Users/marcolopez/Workspace/volumes/ep-net/redis/local/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - default
    environment:
      - REDIS_ARGS=--requirepass PasswordRedis

networks:
  default:
    external: true
    name: employees-promotion-net
