services:
  mongo-promotion:
    image: mongo
    container_name: mongo-promotion
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoPromPass
      MONGO_INITDB_DATABASE: db_promotion
    networks:
      - default
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-promotion-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - /Users/marcolopez/Workspace/volumes/ep-net/mongo-promotion/data:/data/db
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - "9097:9097"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=MongoPromPass
      - ME_CONFIG_MONGODB_URL=mongodb://root:MongoPromPass@mongo-promotion:27017/db_promotion?authSource=admin
    depends_on:
      - mongo-promotion
    networks:
      - default

networks:
  default:
    external: true
    name: employees-promotion-net
