services:
  prometheus:
    image: prom/prometheus:v2.24.0
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9098:9090"
    volumes:
      - ./prometheus/config/:/etc/prometheus/
    command:
        - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - default

  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - default

  promtail:
    image: grafana/promtail:2.9.2
    container_name: promtail
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - default

  grafana:
    image: grafana/grafana-oss:8.5.22
    pull_policy: always
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password1234
      - GF_SERVER_DOMAIN=localhost
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    networks:
      - default

networks:
  default:
    external: true
    name: employees-promotion-net