services:
  vault:
    image: hashicorp/vault:1.18
    container_name: vault
    ports:
      - "8200:8200"
    restart: unless-stopped
    environment:
        - VAULT_ADDR=http://0.0.0.0:8200
        - VAULT_API_ADDR=http://0.0.0.0:8200
        - VAULT_ADDRESS=http://0.0.0.0:8200
    volumes:
      - /Users/marcolopez/Workspace/volumes/ep-net/vault/file:/vault/file:rw
      - /Users/marcolopez/Workspace/volumes/ep-net/vault/config:/vault/file:rw
      - ./scripts/vault.json:/vault/config/vault.json:rw
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json
    networks:
      - default

networks:
  default:
    external: true
    name: employees-promotion-net