services:
  jasperserver-db:
    image: docker.io/bitnami/postgresql:14.7.0
    container_name: jasperserver-db
    restart: unless-stopped
    environment:
      - POSTGRESQL_PASSWORD=password123
      - POSTGRESQL_USERNAME=bn_jasperreports
      - POSTGRESQL_DATABASE=bitnami_jasperreports
    volumes:
      - /Users/marcolopez/Workspace/volumes/ep-net/jasperserver/db/datapg:/bitnami/postgresql
    networks:
      - default
    user: root

  jasperserver-ui:
    image: docker.io/bitnami/jasperreports:8
    container_name: jasperserver-ui
    restart: unless-stopped
    volumes:
      - /Users/marcolopez/Workspace/volumes/ep-net/jasperserver/ui/data:/bitnami/jasperreports
    depends_on:
      - jasperserver-db
    ports:
      - "9030:8080"
    environment:
      - JASPERREPORTS_DATABASE_TYPE=postgresql
      - JASPERREPORTS_DATABASE_HOST=jasperserver-db
      - JASPERREPORTS_DATABASE_PORT_NUMBER=5432
      - JASPERREPORTS_DATABASE_USER=bn_jasperreports
      - JASPERREPORTS_DATABASE_PASSWORD=password123
      - JASPERREPORTS_DATABASE_NAME=bitnami_jasperreports
    networks:
      - default
    user: root

networks:
  default:
    external: true
    name: employees-promotion-net