server:
  port: ${CUSTOM.SERVER.PORT:8002}

encrypt:
  key: ${ENCRYPT.KEY:employees-promotion-secret-key}

spring:
  application:
    name: ms-criteria
  datasource:
    url: jdbc:postgresql://${db-host}:${db-port}/${db-name}
    username: ${db-username}
    password: ${db-password}
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic

resilience4j:
  circuitbreaker:
    instances:
      cliente-service:
        register-health-indicator: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED

logging:
  level:
    org.hibernate.SQL: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
  file:
    name: ${LOG.FILE.PATH:./logs}/${LOG.FILE.NAME:ms-criteria.log}

management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN.ENDPOINT:http://localhost:9411/api/v2/spans}
  auditevents:
    enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
    health:
      show-details: always
      show-components: always
  info:
    env:
      enabled: true
  health:
    env:
      enabled: true
  endpoint:
    health:
      group:
        custom:
          include: diskSpace, ping, memory, mem
          show-component: always
          show-details: always
    logfile:
      external_file: ${LOG.FILE.PATH:./logs}/${LOG.FILE.NAME:ms-employee.log}
