server:
  port: ${CUSTOM.SERVER.PORT:8000}

encrypt:
  key: ${ENCRYPT.KEY:employees-promotion-secret-key}

db:
  host: '{vault}:epp/dev/ms-employee#db-host'
  port: '{vault}:epp/dev/ms-employee#db-port'
  name: '{vault}:epp/dev/ms-employee#db-name'
  username: '{vault}:epp/dev/ms-employee#db-username'
  password: '{vault}:epp/dev/ms-employee#db-password'

spring:
  application:
    name: ms-employee
  datasource:
    url: jdbc:postgresql://${db.host}:${db.port}/${db.name}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

logging:
  level:
    org.hibernate.SQL: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
  file:
    name: ${LOG.FILE.PATH:./logs}/${LOG.FILE.NAME:ms-employee.log}

management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN.ENDPOINT:http://localhost:9411/api/v2/spans}
  auditevents:
    enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
    health:
      show-details: always
      show-components: always
  info:
    env:
      enabled: true
  health:
    env:
      enabled: true
  endpoint:
    health:
      group:
        custom:
          include: diskSpace, ping, memory, mem
          show-component: always
          show-details: always
    logfile:
      external_file: ${LOG.FILE.PATH:./logs}/${LOG.FILE.NAME:ms-employee.log}
