scrape_configs:

  - job_name: 'MS Employee'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['192.168.18.9:8000']
        labels:
          application: 'MS Employee'

  - job_name: 'Monitoring Service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['192.168.18.9:8889']
        labels:
          application: 'Monitoring Service'
